In [2]:
import torch

In [3]:
a = torch.randn(2,10)
a

tensor([[-0.5990,  0.4897, -0.1886,  1.7857,  0.3740,  1.5053, -1.9123, -0.0031,
          0.2243, -0.0043],
        [-0.2527, -0.2407, -0.1008, -1.0413, -2.5178, -0.3817,  1.7822, -1.8828,
          1.2530, -0.4787]])

In [5]:
a.numpy().shape

(2, 10)

In [21]:
b = a.quantile(q=0.1, dim=1)
b

tensor([-1.1311, -0.5486])

In [30]:
b[:,None].shape

torch.Size([2, 1])

In [26]:
b[:, None] * a

tensor([[-0.6263,  1.2348, -0.3247, -1.2889, -0.1722,  1.6807, -1.0656,  0.8712,
         -0.8579,  0.4561],
        [ 0.1821, -0.3035, -0.6601, -0.0502, -0.4668,  0.5254, -0.2554, -0.2703,
          0.2760,  0.1117]])

In [1]:
a = torch.rand(2,3)

NameError: name 'torch' is not defined

In [33]:
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_200\easyspaic_200\parameters\_parameters_dict.pt")

{'autoname1<net>_connection1<con>:autoname1<net>_layer1<neg><-autoname1<net>_input<nod>:{weight}': tensor([[ 4.1030e-02,  1.1099e-01,  1.2017e-01,  3.6737e-02,  1.1753e-01,
           2.6561e-03,  2.3665e-02,  5.0946e-02, -8.5240e-02, -6.9423e-02],
         [-7.1455e-02,  1.0498e-01,  2.7486e-03, -1.0062e-01,  4.9891e-05,
          -1.6446e-02,  6.9711e-02,  1.0696e-01,  1.7018e-02,  4.1191e-02]],
        device='cuda:0', requires_grad=True)}