In [23]:
import os
import sys
import numpy as np
import torch
from darwin3_runtime_api import darwin3_device

# test = darwin3_device.darwin3_device(app_path='../', step_size=10000, ip=['192.168.1.90']) # 172.31.111.35
test = darwin3_device.darwin3_device(app_path='../', step_size=1_000_000, ip=['172.31.111.35'], spk_print=True) # 172.31.111.35

import time


time.sleep(1)

test.reset()

time.sleep(1)

test.darwin3_init(333)

time.sleep(1)

test.deploy_config()

Please check the information on the Darwin3 development board 
to determine if the configuration was successful.
Please check the information on the Darwin3 development board 
to determine if the configuration was successful.


In [132]:
"""
    | 0     1     2    3  |   4    5  |  6    7  |  9      10  |   11    12     13 |     14    15   |   8    |
    | 白    红    蓝  表扬 |  红    蓝 |  酒   酒 |  表扬   批评 |   上    下     挥  |    电低  电低  |   白    |     
       if data[0][2] == 1 or data[0][5] == 1 or data[0][10] == 1 or data[0][12] == 1:
            return EMO["ANGRY"] # 
        
        elif data[0][15] == 1 or  data[0][14] == 1 or data[0][7] == 1 or data[0][6] == 1 or data[0][4] == 1 or data[0][1] == 1:
            return EMO['NEGATIVE']
        
        elif data[0][0] == 1 or data[0][3] == 1 or data[0][8] == 1 or data[0][9] == 1 or data[0][11] == 1 or data[0][13] == 1:
            return EMO['POSITIVE']
    """

def random_input():
    import random 
    input_node_num = 16
    input_num_mul_index = 16

    groups = {
        'ANGRY':    [2, 5, 10, 12],
        'NEGATIVE': [1, 4, 6, 7, 14, 15], # 这里的一个很大的假设就是,如果一起训练可以消极, 那么单个的输入给进来的时候,希望也是消极的!!!!!!
        'POSITIVE': [0, 3, 8, 9, 11, 13],
        }
    selected_group = random.choice(list(groups.values()))
    result_list = [0.0] * input_node_num
    for i in range(input_node_num):
        if i in selected_group:
            result_list[i] = 1.0
        else:
            result_list[i] = random.uniform(0, 0.2)
    print(result_list * input_num_mul_index)
random_input()

[1.0, 0.07946762259613788, 0.004352611368953108, 1.0, 0.11819240436003847, 0.12901320919485704, 0.15647942537575954, 0.04364553866590464, 1.0, 1.0, 0.02180436236892147, 1.0, 0.11734203255358051, 1.0, 0.07828103991408271, 0.0286201610391275, 1.0, 0.07946762259613788, 0.004352611368953108, 1.0, 0.11819240436003847, 0.12901320919485704, 0.15647942537575954, 0.04364553866590464, 1.0, 1.0, 0.02180436236892147, 1.0, 0.11734203255358051, 1.0, 0.07828103991408271, 0.0286201610391275, 1.0, 0.07946762259613788, 0.004352611368953108, 1.0, 0.11819240436003847, 0.12901320919485704, 0.15647942537575954, 0.04364553866590464, 1.0, 1.0, 0.02180436236892147, 1.0, 0.11734203255358051, 1.0, 0.07828103991408271, 0.0286201610391275, 1.0, 0.07946762259613788, 0.004352611368953108, 1.0, 0.11819240436003847, 0.12901320919485704, 0.15647942537575954, 0.04364553866590464, 1.0, 1.0, 0.02180436236892147, 1.0, 0.11734203255358051, 1.0, 0.07828103991408271, 0.0286201610391275, 1.0, 0.07946762259613788, 0.00435261136

In [31]:
test.reset()


Please check the information on the Darwin3 development board 
to determine if the configuration was successful.


In [32]:
test.darwin3_init(333)

Please check the information on the Darwin3 development board 
to determine if the configuration was successful.


In [33]:
test.deploy_config()

In [183]:
test_ls.append([])


NameError: name 'test_ls' is not defined

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['wgtsum1',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？
test.get_neuron_state(pop_name="layer2", state=[ [i, ['wgtsum1',],] for i in range(100) ]) # 电压增大导致 第二层脉冲触发了， nice 发现问题 解决问题
test.get_neuron_state(pop_name="layer1", state=[ [i, ['wgtsum0',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？
test.get_neuron_state(pop_name="layer2", state=[ [i, ['wgtsum0',],] for i in range(100) ]) # 电压增大导致 第二层脉冲触发了， nice 发现问题 解决问题

In [58]:
np.exp(-1/20)

0.951229424500714

In [ ]:
100 * 255

0.9375

In [22]:
import time
t = time.perf_counter()
test.get_neuron_state(pop_name="layer1", state=[ [i, ['dedr',],] for i in range(4740) ]) # 这里 是读取权重的代码
print("time cost: ",time.perf_counter() - t)

time cost:  0.2406450999997105


In [344]:
# print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer1", state=[ [i, ['vt',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？
test.get_neuron_state(pop_name="layer2", state=[ [i, ['vt',],] for i in range(100) ]) # 电压增大导致 第二层脉冲触发了， nice 发现问题 解决问题

In [2]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['learning_status',],] for i in range(355) ]) # prt1ax 看最后7位

In [7]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['learning_status_dendrite',],] for i in range(355) ]) # prt1ax 看最后7位

In [ ]:
test.run_darwin3_withoutfile([[]])

# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],] ]) # 查看work mod
# test.get_neuron_state(pop_name="layer1", state=[ [i, ['inference_status',],] for i in range(100) ]) # 
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],] ]) # 查看work mod
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],] ], offset=0x05) # 查看work mod


[[]]

In [4]:
import numpy as np
def input_func(input_ls, unit_conversion=0.8, dt=0.1):# 这连个参数对标spaic的possion_encoder
    # import numpy as np
    # rand_input = np.where(np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    a = (np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    return np.nonzero(a[0].astype(int))[0]

input_ls = np.array([[1 if i==3 else 0 for i in range(256)]])
a = input_func(input_ls=input_ls)
print(a)
out = test.run_darwin3_withoutfile(spike_neurons=[a])
print(out)

[]
[[]]


In [61]:
test.run_darwin3_withoutfile(spike_neurons=[[5]])

[[]]

In [4]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],] ]) # 查看work mod

In [177]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['learning_status',],],  [1, ['learning_status',],] ]) # 查看work mod

In [53]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['config_reg',],],  [1, ['config_reg',],] ], offset=0x19) # 查看work mod

In [2]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['config_reg',],],  [1, ['config_reg',],] ], offset=0x0B) # 查看 pra0

yyyyyy
yyyyyy


In [5]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['config_reg',],],  [1, ['config_reg',],] ], offset=0x02) # 查看 workmode

yyyyyy
yyyyyy


In [3]:
test.get_neuron_state(pop_name="layer2", state=[ [0, ['config_reg',],],  [1, ['config_reg',],] ], offset=0x08) # 查看 workmod

yyyyyy
yyyyyy


In [174]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['inference_status',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？

In [193]:
test.run_darwin3_withoutfile([[]])

[[]]

In [26]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['learning_status',],] for i in range(355) ]) # prt1ax 看最后7位

In [196]:
test.clear_neurons_states(LSC=True)

In [ ]:
import numpy as np
def random_input():
    # 返回一个 (1 * 256) 的 np.array, 内容是 对不同情感的 groups 的 是 1 其余 是 0 
    import random 
    input_node_num = 16
    input_num_mul_index = 16
    groups = {
        'ANGRY':    [2, 5, 10, 12],
        'NEGATIVE': [1, 4, 6, 7, 14, 15], # 这里的一个很大的假设就是,如果一起训练可以消极, 那么单个的输入给进来的时候,希望也是消极的!!!!!!
        'POSITIVE': [0, 3, 8, 9, 11, 13],
        }
    selected_group = random.choice(list(groups.values()))
    result_list = [0.0] * input_node_num
    for i in range(input_node_num):
        if i in selected_group:
            result_list[i] = 1 
        else:
            result_list[i] = 0
    # print(list(map(int , result_list)))
    
    return np.array([result_list * input_num_mul_index]) # 扩充了一个维度


def input_func(input_ls, unit_conversion=0.4, dt=0.1):# 这连个参数对标spaic的possion_encoder
    # 这里加了一层 随机性, 但其实还是要在 阈值放大来看,而不是 在这里一度的缩小
    a = (np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt) # a 是一个 true 和 false 的同维度 array
    return np.nonzero(a[0].astype(int))[0] # 返回一个 nozero 的 list  这里体现除了 darwin 的输入特点， 只对需要的内容 输入， 0代表的是 0 号神经元输入，

def step():
    # 这里就是标准的 正向传播的代码
    ls = np.zeros(100,) # 这个变量用来 记录 一个 time step 时间周期内  有多少个编号的 激活层 的 神经元会脉冲
    test.clear_neurons_states(LSC=True) # 学习状态存储器清空
    input_ls = random_input()   # 获取随即输入
    
    a = input_func(input_ls) # 处理成 非零的值 的list
    
    for _ in range(25):
        out = test.run_darwin3_withoutfile(spike_neurons=[a]) # 一次传播
        for i in range(len(out[0])):
            index = out[0][i][1]
            ls[index] += 1 # ls 保存的就是 激活层 的脉冲神经元 的脉冲次数, 

    print(ls.nonzero()) # 这里返回的是 编号
    # print(ls[ls.nonzero()])
for i in range(1): # 跑100次 读一下权重
    step()

# 那这样的话就是调出来了。 下面就是要把  Darwin的初始化还有step 的函数 放到 狗的代码里面 把spaic 的位置换成darwin stdp

(array([15, 17, 21, 22, 33, 36, 55, 56, 85], dtype=int64),)


In [172]:
import random
groups = {
    'ANGRY':    [2, 5, 10, 12],
    'NEGATIVE': [1, 4, 6, 7, 14, 15], # 这里的一个很大的假设就是,如果一起训练可以消极, 那么单个的输入给进来的时候,希望也是消极的!!!!!!
    'POSITIVE': [0, 3, 8, 9, 11, 13],
    }
random.choice(list(groups.values()))

[2, 5, 10, 12]

In [24]:
def input_func(input_ls, unit_conversion=0.7, dt=0.1):# 这连个参数对标spaic的possion_encoder
    # import numpy as np
    # rand_input = np.where(np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    a = (np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    return np.nonzero(a[0].astype(int))[0]

def step():
    ls = np.zeros(100,)
    test.clear_neurons_states(LSC=True) # 学习状态存储器清空
    for _ in range(25):
        input_ls = np.array([[1 if i==1 or i == 4 else 0.01 for i in range(16)] * 16])
        a = input_func(input_ls)
        # print(a)

        out = test.run_darwin3_withoutfile(spike_neurons=[a])
        # print(out)
        for i in range(len(out[0])):
            index = out[0][i][1]
            ls[index] += 1 # ls 保存的就是 激活层 的脉冲神经元 的脉冲次数, 
    print(ls.nonzero())
import time
t = time.perf_counter()
for i in range(100): # 跑100次 读一下权重
    step()
print("time cost: ",time.perf_counter() - t)

(array([ 5, 12, 28, 31, 57, 60, 66, 71, 76, 91], dtype=int64),)
(array([ 5, 12, 28, 31, 57, 60, 66, 71, 76, 91], dtype=int64),)
(array([ 5, 12, 28, 31, 57, 60, 66, 71, 76, 91], dtype=int64),)
(array([], dtype=int64),)
(array([ 5, 12, 28, 31, 57, 60, 66, 71, 76, 91], dtype=int64),)
(array([ 1,  5, 12, 28, 31, 41, 57, 60, 64, 66, 71, 76, 91], dtype=int64),)
(array([ 5, 12, 28, 31, 57, 60, 64, 66, 71, 76, 91], dtype=int64),)
(array([], dtype=int64),)
(array([ 5, 12, 28, 31, 57, 60, 64, 66, 71, 76, 91], dtype=int64),)
(array([ 5, 12, 28, 31, 57, 60, 66, 71, 76, 91], dtype=int64),)
(array([ 5, 12, 28, 31, 57, 60, 64, 66, 71, 76, 91], dtype=int64),)
(array([], dtype=int64),)
(array([ 5, 12, 28, 31, 57, 60, 64, 66, 71, 76, 91], dtype=int64),)
(array([ 5, 12, 28, 31, 57, 60, 64, 66, 71, 76, 91], dtype=int64),)
(array([ 5, 12, 28, 31, 57, 60, 64, 66, 71, 76, 91], dtype=int64),)
(array([ 5, 12, 28, 31, 57, 60, 64, 66, 71, 76, 91], dtype=int64),)
(array([ 5, 12, 28, 31, 57, 60, 64, 66, 71, 76, 91

In [25]:
import time
t = time.perf_counter()
test.get_neuron_state(pop_name="layer1", state=[ [i, ['dedr',],] for i in range(4740) ]) # 这里 是读取权重的代码
print("time cost: ",time.perf_counter() - t)

time cost:  0.2763749999994616


In [96]:
test.run_darwin3_withoutfile(spike_neurons=[[]])

[[('output_pop', 5),
  ('output_pop', 23),
  ('output_pop', 36),
  ('output_pop', 48),
  ('output_pop', 65),
  ('output_pop', 71),
  ('output_pop', 81),
  ('output_pop', 90)]]

In [7]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x08)

8
8


In [254]:
def input_func(input_ls, unit_conversion=0.8, dt=0.1):# 这连个参数对标spaic的possion_encoder
    # import numpy as np
    # rand_input = np.where(np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    a = (np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)

    return np.nonzero(a[0].astype(int))[0]

In [3]:
import numpy as np
import torch

In [4]:
a = torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\quant_input_layer1.pth")
a

tensor([[126.,  19.,  39.,  ...,  71.,  34.,  25.],
        [ 67.,  75.,  18.,  ...,  45.,  21.,  66.],
        [ 44.,  56.,  83.,  ...,  25.,  63., 109.],
        ...,
        [ 99.,  43.,  86.,  ..., 127., 114.,  48.],
        [123.,  67.,  39.,  ..., 105.,  42.,  78.],
        [ 92.,  52.,  49.,  ..., 127.,  47.,  39.]], device='cuda:0',
       requires_grad=True)

In [5]:
a[0]

tensor([126.,  19.,  39.,  59.,  31.,  26.,  24.,  32., 125.,  68.,  17.,  74.,
         31.,  64.,  18.,  33., 127.,  11.,  24.,  69.,  22.,  40.,  12.,  42.,
        119.,  72.,  28.,  56.,  37.,  64.,  19.,  25., 125.,  20.,  25.,  61.,
         16.,  37.,  26.,  34., 120.,  55.,  19.,  76.,  54.,  61.,  30.,  25.,
        111.,  23.,  20.,  54.,  23.,  30.,  18.,  34., 119.,  57.,  19.,  65.,
         48.,  65.,  22.,  27., 127.,  15.,  39.,  67.,  17.,  23.,  23.,  34.,
        120.,  43.,  21.,  60.,  47.,  67.,  24.,  29., 127.,  14.,  31.,  44.,
         24.,  24.,  31.,  35., 122.,  66.,  21.,  66.,  35.,  67.,  19.,  26.,
        127.,   9.,  25.,  44.,  47.,  29.,  20.,  29., 110.,  61.,  14.,  66.,
         54.,  64.,  21.,  32., 120.,  22.,  27.,  56.,  31.,  39.,  26.,  37.,
        110.,  49.,  24.,  73.,  33.,  61.,  18.,  31., 118.,  22.,  27.,  61.,
         16.,  29.,  16.,  43., 113.,  52.,  27.,  56.,  26.,  64.,  22.,  19.,
        127.,  19.,  32.,  58.,  37.,  3

In [71]:
test.get_neuron_state(pop_name="layer2", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]])  # 19

In [6]:
len("2024-12-10 14:22:10,514 - INFO - [dedr] tik=0, x=0, y=2, relay_link=0x00, addr=0x")

81

In [ ]:

import time
for _ in range(25):
    print(test.run_darwin3_withoutfile(spike_neurons=[[]])) # 
    # time.sleep(0.4)
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]])  # 19

In [36]:
print(test.run_darwin3_withoutfile(spike_neurons=[[]])) # 


[[]]


In [ ]:
print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器

In [ ]:
test.get_neuron_state(pop_name="layer2", state=[ [i, ['vt',],] for i in range(100) ])

In [37]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x01) # 查看vth 寄存器
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x02) # 查看vth 寄存器
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x03) # 查看vth 寄存器

1
1
2
2
3
3


In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])

In [ ]:
import time

In [ ]:
for i in range(100):
    test.get_neuron_state(pop_name="layer1", state=[ [i, ['vt',],], ])
    time.sleep(0.5)


In [ ]:
print(test.run_darwin3_withoutfile(spike_neurons=test_ls))


In [ ]:
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器
print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器


In [12]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x02)

2
2


In [ ]:

print(test.run_darwin3_withoutfile(spike_neurons=[[7,]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])

# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器 这是 第四次 输入 应该进入了下一个周期，所以应该电压会相对高一点

In [ ]:
print(test.run_darwin3_withoutfile(spike_neurons=[[7,8,9]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])


In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x01)

In [ ]:
test.run_darwin3_withoutfile(spike_neurons=[[5,6,7,8],[]])
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]])

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x05) # 查看vth 寄存器

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_lif_200_quant\parameters\_variables.pt")

In [ ]:
test.run_darwin3_withoutfile(spike_neurons=[[]])

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x00)

In [ ]:
test.run_darwin3_withoutfile(spike_neurons=test_ls)

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_200_quant\parameters\_parameters_dict.pt") # 加载权重
# weight_input0_to_layer1 = emo_net_weight[r'autoname9<net>_connection1<con>:autoname9<net>_layer1<neg><-autoname9<net>_input<nod>:{weight}'].detach().cpu() # 

In [ ]:
vth = torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_200\parameters\_variables.pt") # 加载权重
vth

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_lif_200_quant\parameters\_variables.pt") # 加载权重

In [ ]:
vth = vth['autoname9<net>_layer1<neg>:{v_th}'].detach().cpu()

In [81]:
hex(0b0100_0100 << 8)

'0x4400'

In [ ]:
import numpy as np

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x00)

In [129]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['config_reg',],],  [1, ['config_reg',],] ], offset=0x08)

yyyyyy
yyyyyy


In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\quant_input_layer1.pth").detach().cpu().numpy()

In [43]:
hex((-1 & 0xff))

'0xff'

In [ ]:
-24000
2**16

In [ ]:
-52 * 400

In [ ]:
3 / 32

In [ ]:
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\hang_zhou_spaic\save_600\real_ysc_model_mic\parameters\_parameters_dict.pt")

In [ ]:
hex(-40*400 & 0xffff)

In [60]:
emo_net_weight = torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\quant_input_layer1.pth").detach().cpu().numpy()
emo_net_weight

array([[126.,  19.,  39., ...,  71.,  34.,  25.],
       [ 67.,  75.,  18., ...,  45.,  21.,  66.],
       [ 44.,  56.,  83., ...,  25.,  63., 109.],
       ...,
       [ 99.,  43.,  86., ..., 127., 114.,  48.],
       [123.,  67.,  39., ..., 105.,  42.,  78.],
       [ 92.,  52.,  49., ..., 127.,  47.,  39.]], dtype=float32)

In [61]:
emo_net_weight.shape

(100, 256)

In [63]:
emo_net_weight[:, 0].shape

(100,)

In [15]:
np.array((-2,2)) ** 2

array([4, 4])