In [89]:
import os
import sys
import numpy as np
import torch
from darwin3_runtime_api import darwin3_device

# test = darwin3_device.darwin3_device(app_path='../', step_size=10000, ip=['192.168.1.90']) # 172.31.111.35
test = darwin3_device.darwin3_device(app_path='../', step_size=10_000_000, ip=['172.31.111.35'], spk_print=True) # 172.31.111.35

import time


time.sleep(1)

test.reset()

time.sleep(1)

test.darwin3_init(333)

time.sleep(1)

test.deploy_config()

Please check the information on the Darwin3 development board 
to determine if the configuration was successful.
Please check the information on the Darwin3 development board 
to determine if the configuration was successful.


In [31]:
test.reset()


Please check the information on the Darwin3 development board 
to determine if the configuration was successful.


In [32]:
test.darwin3_init(333)

Please check the information on the Darwin3 development board 
to determine if the configuration was successful.


In [33]:
test.deploy_config()

In [ ]:
test_ls.append([])


In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['wgtsum1',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？
test.get_neuron_state(pop_name="layer2", state=[ [i, ['wgtsum1',],] for i in range(100) ]) # 电压增大导致 第二层脉冲触发了， nice 发现问题 解决问题
test.get_neuron_state(pop_name="layer1", state=[ [i, ['wgtsum0',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？
test.get_neuron_state(pop_name="layer2", state=[ [i, ['wgtsum0',],] for i in range(100) ]) # 电压增大导致 第二层脉冲触发了， nice 发现问题 解决问题

In [344]:
# print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer1", state=[ [i, ['vt',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？
test.get_neuron_state(pop_name="layer2", state=[ [i, ['vt',],] for i in range(100) ]) # 电压增大导致 第二层脉冲触发了， nice 发现问题 解决问题

In [39]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['learning_status',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？


error! not allowed %s learning_status


UnboundLocalError: local variable 'item' referenced before assignment

In [91]:
test.run_darwin3_withoutfile([[]])
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],] ]) # 查看work mod
test.get_neuron_state(pop_name="layer1", state=[ [i, ['inference_status',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],] ]) # 查看work mod
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],] ], offset=0x05) # 查看work mod


In [78]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],] ]) # 查看work mod

In [53]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['config_reg',],],  [1, ['config_reg',],] ], offset=0x19) # 查看work mod

In [79]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['inference_status',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？

In [80]:
ls = np.zeros(100,)
def input_func(input_ls, unit_conversion=0.8, dt=0.1):# 这连个参数对标spaic的possion_encoder
    # import numpy as np
    # rand_input = np.where(np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    a = (np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    return np.nonzero(a[0].astype(int))[0]

for _ in range(25):
    input_ls = np.array([[1 if i==1 or i == 4 else 0.01 for i in range(16)] * 16])
    a = input_func(input_ls)
    out = test.run_darwin3_withoutfile(spike_neurons=[a])

    for i in range(len(out[0])):
        index = out[0][i][1]
        ls[index] += 1
print(ls.nonzero())
print(ls[ls.nonzero()])




# 那这样的话就是调出来了。 下面就是要把  Darwin的初始化还有step 的函数 放到 狗的代码里面 把spaic 的位置换成darwin stdp

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int64),)
[15. 14. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]


In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x02)

2
2


In [254]:
def input_func(input_ls, unit_conversion=0.8, dt=0.1):# 这连个参数对标spaic的possion_encoder
    # import numpy as np
    # rand_input = np.where(np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    a = (np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)

    return np.nonzero(a[0].astype(int))[0]

In [85]:
import numpy as np

In [140]:
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\quant_input_layer1.pth")

tensor([[126.,  19.,  39.,  ...,  71.,  34.,  25.],
        [ 67.,  75.,  18.,  ...,  45.,  21.,  66.],
        [ 44.,  56.,  83.,  ...,  25.,  63., 109.],
        ...,
        [ 99.,  43.,  86.,  ..., 127., 114.,  48.],
        [123.,  67.,  39.,  ..., 105.,  42.,  78.],
        [ 92.,  52.,  49.,  ..., 127.,  47.,  39.]], device='cuda:0',
       requires_grad=True)

In [71]:
test.get_neuron_state(pop_name="layer2", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]])  # 19

In [ ]:

import time
for _ in range(25):
    print(test.run_darwin3_withoutfile(spike_neurons=[[]])) # 
    # time.sleep(0.4)
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]])  # 19

In [ ]:
print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器

In [ ]:
test.get_neuron_state(pop_name="layer2", state=[ [i, ['vt',],] for i in range(100) ])

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x05) # 查看vth 寄存器

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])

In [ ]:
import time

In [ ]:
for i in range(100):
    test.get_neuron_state(pop_name="layer1", state=[ [i, ['vt',],], ])
    time.sleep(0.5)


In [ ]:
print(test.run_darwin3_withoutfile(spike_neurons=test_ls))


In [ ]:
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器
print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器


In [12]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x02)

2
2


In [ ]:

print(test.run_darwin3_withoutfile(spike_neurons=[[7,]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])

# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器 这是 第四次 输入 应该进入了下一个周期，所以应该电压会相对高一点

In [ ]:
print(test.run_darwin3_withoutfile(spike_neurons=[[7,8,9]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])


In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x01)

In [ ]:
test.run_darwin3_withoutfile(spike_neurons=[[5,6,7,8],[]])
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]])

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x05) # 查看vth 寄存器

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_lif_200_quant\parameters\_variables.pt")

In [ ]:
test.run_darwin3_withoutfile(spike_neurons=[[]])

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x00)

In [ ]:
test.run_darwin3_withoutfile(spike_neurons=test_ls)

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_200_quant\parameters\_parameters_dict.pt") # 加载权重
# weight_input0_to_layer1 = emo_net_weight[r'autoname9<net>_connection1<con>:autoname9<net>_layer1<neg><-autoname9<net>_input<nod>:{weight}'].detach().cpu() # 

In [ ]:
vth = torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_200\parameters\_variables.pt") # 加载权重
vth

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_lif_200_quant\parameters\_variables.pt") # 加载权重

In [ ]:
vth = vth['autoname9<net>_layer1<neg>:{v_th}'].detach().cpu()

In [ ]:
vth

In [ ]:
import numpy as np

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x00)

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['config_reg',],],  [1, ['config_reg',],] ], offset=0x16)

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\quant_input_layer1.pth").detach().cpu().numpy()

In [ ]:
a[55]

In [ ]:
-24000
2**16

In [ ]:
-52 * 400

In [ ]:
3 / 32

In [ ]:
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\hang_zhou_spaic\save_600\real_ysc_model_mic\parameters\_parameters_dict.pt")

In [ ]:
hex(-40*400 & 0xffff)

In [60]:
emo_net_weight = torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\quant_input_layer1.pth").detach().cpu().numpy()
emo_net_weight

array([[126.,  19.,  39., ...,  71.,  34.,  25.],
       [ 67.,  75.,  18., ...,  45.,  21.,  66.],
       [ 44.,  56.,  83., ...,  25.,  63., 109.],
       ...,
       [ 99.,  43.,  86., ..., 127., 114.,  48.],
       [123.,  67.,  39., ..., 105.,  42.,  78.],
       [ 92.,  52.,  49., ..., 127.,  47.,  39.]], dtype=float32)

In [61]:
emo_net_weight.shape

(100, 256)

In [63]:
emo_net_weight[:, 0].shape

(100,)