In [16]:
import os
import sys
import numpy as np
import torch
from darwin3_runtime_api import darwin3_device

# test = darwin3_device.darwin3_device(app_path='../', step_size=10000, ip=['192.168.1.90']) # 172.31.111.35
test = darwin3_device.darwin3_device(app_path='../', step_size=1_000_000, ip=['172.31.111.35'], spk_print=True) # 172.31.111.35

import time


time.sleep(1)

test.reset()

time.sleep(1)

test.darwin3_init(333)

time.sleep(1)

test.deploy_config()

Please check the information on the Darwin3 development board 
to determine if the configuration was successful.
Please check the information on the Darwin3 development board 
to determine if the configuration was successful.


In [31]:
test.reset()


Please check the information on the Darwin3 development board 
to determine if the configuration was successful.


In [32]:
test.darwin3_init(333)

Please check the information on the Darwin3 development board 
to determine if the configuration was successful.


In [33]:
test.deploy_config()

In [183]:
test_ls.append([])


NameError: name 'test_ls' is not defined

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['wgtsum1',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？
test.get_neuron_state(pop_name="layer2", state=[ [i, ['wgtsum1',],] for i in range(100) ]) # 电压增大导致 第二层脉冲触发了， nice 发现问题 解决问题
test.get_neuron_state(pop_name="layer1", state=[ [i, ['wgtsum0',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？
test.get_neuron_state(pop_name="layer2", state=[ [i, ['wgtsum0',],] for i in range(100) ]) # 电压增大导致 第二层脉冲触发了， nice 发现问题 解决问题

In [58]:
np.exp(-1/20)

0.951229424500714

In [ ]:
100 * 255

0.9375

In [18]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['dedr',],] for i in range(4740) ])

In [344]:
# print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer1", state=[ [i, ['vt',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？
test.get_neuron_state(pop_name="layer2", state=[ [i, ['vt',],] for i in range(100) ]) # 电压增大导致 第二层脉冲触发了， nice 发现问题 解决问题

In [2]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['learning_status',],] for i in range(355) ]) # prt1ax 看最后7位

In [7]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['learning_status_dendrite',],] for i in range(355) ]) # prt1ax 看最后7位

In [6]:
hex((-100 & 0xffff)<<16)

'0xff9c0000'

In [ ]:
int(hex((-1 & 0xff)<<8), 16)

65280

In [16]:
0x01 | int(hex((-1 & 0xff)<<8), 16)

65281

In [ ]:
test.run_darwin3_withoutfile([[]])

# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],] ]) # 查看work mod
# test.get_neuron_state(pop_name="layer1", state=[ [i, ['inference_status',],] for i in range(100) ]) # 
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],] ]) # 查看work mod
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],] ], offset=0x05) # 查看work mod


[[]]

In [4]:
import numpy as np
def input_func(input_ls, unit_conversion=0.8, dt=0.1):# 这连个参数对标spaic的possion_encoder
    # import numpy as np
    # rand_input = np.where(np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    a = (np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    return np.nonzero(a[0].astype(int))[0]

input_ls = np.array([[1 if i==3 else 0 for i in range(256)]])
a = input_func(input_ls=input_ls)
print(a)
out = test.run_darwin3_withoutfile(spike_neurons=[a])
print(out)

[]
[[]]


In [61]:
test.run_darwin3_withoutfile(spike_neurons=[[5]])

[[]]

In [4]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],] ]) # 查看work mod

In [177]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['learning_status',],],  [1, ['learning_status',],] ]) # 查看work mod

In [53]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['config_reg',],],  [1, ['config_reg',],] ], offset=0x19) # 查看work mod

In [2]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['config_reg',],],  [1, ['config_reg',],] ], offset=0x0B) # 查看 pra0

yyyyyy
yyyyyy


In [41]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['config_reg',],],  [1, ['config_reg',],] ], offset=0x02) # 查看 workmode

yyyyyy
yyyyyy


In [174]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['inference_status',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？

In [193]:
test.run_darwin3_withoutfile([[]])

[[]]

In [6]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['learning_status',],] for i in range(355) ]) # prt1ax 看最后7位

In [196]:
test.clear_neurons_states(LSC=True)

In [17]:
def input_func(input_ls, unit_conversion=0.8, dt=0.1):# 这连个参数对标spaic的possion_encoder
    # import numpy as np
    # rand_input = np.where(np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    a = (np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    return np.nonzero(a[0].astype(int))[0]

def step():
    ls = np.zeros(100,)
    test.clear_neurons_states(LSC=True) # 学习状态存储器清空
    for _ in range(25):
        input_ls = np.array([[1 if i==1 or i == 4 else 0.01 for i in range(16)] * 16])
        a = input_func(input_ls)
        # print(a)
        out = test.run_darwin3_withoutfile(spike_neurons=[a])

        for i in range(len(out[0])):
            index = out[0][i][1]
            ls[index] += 1
    print(ls.nonzero())
    # print(ls[ls.nonzero()])

for i in range(100): # 跑100次 读一下权重
    step()

# 那这样的话就是调出来了。 下面就是要把  Darwin的初始化还有step 的函数 放到 狗的代码里面 把spaic 的位置换成darwin stdp

(array([12, 28, 31, 57, 60, 66, 71, 76, 91], dtype=int64),)
(array([12, 28, 31, 57, 60, 66, 71, 76, 91], dtype=int64),)
(array([12, 28, 31, 57, 60, 66, 76, 91], dtype=int64),)
(array([12, 28, 31, 57, 60, 66, 76], dtype=int64),)
(array([12, 28, 31, 57, 60, 66, 76, 91], dtype=int64),)
(array([12, 28, 31, 41, 57, 60, 66, 71, 76, 91], dtype=int64),)
(array([ 4, 12, 28, 31, 41, 57, 60, 66, 71, 76, 77, 91], dtype=int64),)
(array([ 4, 12, 14, 22, 28, 31, 41, 49, 57, 60, 66, 71, 76, 91],
      dtype=int64),)
(array([12, 28, 31, 57, 60, 66, 71, 76, 91], dtype=int64),)
(array([ 1,  4,  8, 12, 28, 31, 41, 57, 60, 66, 71, 76, 77, 91],
      dtype=int64),)
(array([12, 28, 31, 57, 60, 66, 71, 76, 91], dtype=int64),)
(array([ 1,  4, 12, 28, 31, 41, 53, 57, 60, 66, 71, 76, 77, 91],
      dtype=int64),)
(array([ 4, 12, 28, 31, 41, 57, 60, 66, 71, 76, 91], dtype=int64),)
(array([12, 28, 31, 57, 60, 66, 76, 91], dtype=int64),)
(array([ 1,  4, 12, 28, 31, 41, 57, 60, 66, 71, 76, 91], dtype=int64),)
(array

In [187]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x06)

6
6


In [254]:
def input_func(input_ls, unit_conversion=0.8, dt=0.1):# 这连个参数对标spaic的possion_encoder
    # import numpy as np
    # rand_input = np.where(np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    a = (np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)

    return np.nonzero(a[0].astype(int))[0]

In [3]:
import numpy as np
import torch

In [4]:
a = torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\quant_input_layer1.pth")
a

tensor([[126.,  19.,  39.,  ...,  71.,  34.,  25.],
        [ 67.,  75.,  18.,  ...,  45.,  21.,  66.],
        [ 44.,  56.,  83.,  ...,  25.,  63., 109.],
        ...,
        [ 99.,  43.,  86.,  ..., 127., 114.,  48.],
        [123.,  67.,  39.,  ..., 105.,  42.,  78.],
        [ 92.,  52.,  49.,  ..., 127.,  47.,  39.]], device='cuda:0',
       requires_grad=True)

In [5]:
a[0]

tensor([126.,  19.,  39.,  59.,  31.,  26.,  24.,  32., 125.,  68.,  17.,  74.,
         31.,  64.,  18.,  33., 127.,  11.,  24.,  69.,  22.,  40.,  12.,  42.,
        119.,  72.,  28.,  56.,  37.,  64.,  19.,  25., 125.,  20.,  25.,  61.,
         16.,  37.,  26.,  34., 120.,  55.,  19.,  76.,  54.,  61.,  30.,  25.,
        111.,  23.,  20.,  54.,  23.,  30.,  18.,  34., 119.,  57.,  19.,  65.,
         48.,  65.,  22.,  27., 127.,  15.,  39.,  67.,  17.,  23.,  23.,  34.,
        120.,  43.,  21.,  60.,  47.,  67.,  24.,  29., 127.,  14.,  31.,  44.,
         24.,  24.,  31.,  35., 122.,  66.,  21.,  66.,  35.,  67.,  19.,  26.,
        127.,   9.,  25.,  44.,  47.,  29.,  20.,  29., 110.,  61.,  14.,  66.,
         54.,  64.,  21.,  32., 120.,  22.,  27.,  56.,  31.,  39.,  26.,  37.,
        110.,  49.,  24.,  73.,  33.,  61.,  18.,  31., 118.,  22.,  27.,  61.,
         16.,  29.,  16.,  43., 113.,  52.,  27.,  56.,  26.,  64.,  22.,  19.,
        127.,  19.,  32.,  58.,  37.,  3

In [71]:
test.get_neuron_state(pop_name="layer2", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]])  # 19

In [6]:
len("2024-12-10 14:22:10,514 - INFO - [dedr] tik=0, x=0, y=2, relay_link=0x00, addr=0x")

81

In [ ]:

import time
for _ in range(25):
    print(test.run_darwin3_withoutfile(spike_neurons=[[]])) # 
    # time.sleep(0.4)
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]])  # 19

In [ ]:
print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器

In [ ]:
test.get_neuron_state(pop_name="layer2", state=[ [i, ['vt',],] for i in range(100) ])

In [189]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x06) # 查看vth 寄存器

6
6


In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])

In [ ]:
import time

In [ ]:
for i in range(100):
    test.get_neuron_state(pop_name="layer1", state=[ [i, ['vt',],], ])
    time.sleep(0.5)


In [ ]:
print(test.run_darwin3_withoutfile(spike_neurons=test_ls))


In [ ]:
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器
print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器


In [12]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x02)

2
2


In [ ]:

print(test.run_darwin3_withoutfile(spike_neurons=[[7,]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])

# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器 这是 第四次 输入 应该进入了下一个周期，所以应该电压会相对高一点

In [ ]:
print(test.run_darwin3_withoutfile(spike_neurons=[[7,8,9]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])


In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x01)

In [ ]:
test.run_darwin3_withoutfile(spike_neurons=[[5,6,7,8],[]])
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]])

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x05) # 查看vth 寄存器

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_lif_200_quant\parameters\_variables.pt")

In [ ]:
test.run_darwin3_withoutfile(spike_neurons=[[]])

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x00)

In [ ]:
test.run_darwin3_withoutfile(spike_neurons=test_ls)

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_200_quant\parameters\_parameters_dict.pt") # 加载权重
# weight_input0_to_layer1 = emo_net_weight[r'autoname9<net>_connection1<con>:autoname9<net>_layer1<neg><-autoname9<net>_input<nod>:{weight}'].detach().cpu() # 

In [ ]:
vth = torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_200\parameters\_variables.pt") # 加载权重
vth

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_lif_200_quant\parameters\_variables.pt") # 加载权重

In [ ]:
vth = vth['autoname9<net>_layer1<neg>:{v_th}'].detach().cpu()

In [81]:
hex(0b0100_0100 << 8)

'0x4400'

In [ ]:
import numpy as np

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x00)

In [129]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['config_reg',],],  [1, ['config_reg',],] ], offset=0x08)

yyyyyy
yyyyyy


In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\quant_input_layer1.pth").detach().cpu().numpy()

In [43]:
hex((-1 & 0xff))

'0xff'

In [ ]:
-24000
2**16

In [ ]:
-52 * 400

In [ ]:
3 / 32

In [ ]:
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\hang_zhou_spaic\save_600\real_ysc_model_mic\parameters\_parameters_dict.pt")

In [ ]:
hex(-40*400 & 0xffff)

In [60]:
emo_net_weight = torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\quant_input_layer1.pth").detach().cpu().numpy()
emo_net_weight

array([[126.,  19.,  39., ...,  71.,  34.,  25.],
       [ 67.,  75.,  18., ...,  45.,  21.,  66.],
       [ 44.,  56.,  83., ...,  25.,  63., 109.],
       ...,
       [ 99.,  43.,  86., ..., 127., 114.,  48.],
       [123.,  67.,  39., ..., 105.,  42.,  78.],
       [ 92.,  52.,  49., ..., 127.,  47.,  39.]], dtype=float32)

In [61]:
emo_net_weight.shape

(100, 256)

In [63]:
emo_net_weight[:, 0].shape

(100,)

In [15]:
np.array((-2,2)) ** 2

array([4, 4])