In [274]:
import os
import sys
import numpy as np
import torch
sys.path.append("../scripts")
from darwin3_runtime_api import darwin3_device
from contextlib import redirect_stdout

# test = darwin3_device.darwin3_device(app_path='../', step_size=10000, ip=['192.168.1.90']) # 172.31.111.35
test = darwin3_device.darwin3_device(app_path='../', step_size=1000_000, ip=['172.31.111.35'], spk_print=True) # 172.31.111.35

In [339]:
test.reset()


Please check the information on the Darwin3 development board 
to determine if the configuration was successful.


In [340]:
test.darwin3_init(333)

Please check the information on the Darwin3 development board 
to determine if the configuration was successful.


In [341]:
test.deploy_config()

In [ ]:
sub_test_ls = [2]
test_ls = [sub_test_ls] * 20
test_ls


In [ ]:
test_ls.append([])


In [178]:
test.get_neuron_state(pop_name="layer1", state=[ [i, ['wgtsum1',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？
test.get_neuron_state(pop_name="layer2", state=[ [i, ['wgtsum1',],] for i in range(100) ]) # 电压增大导致 第二层脉冲触发了， nice 发现问题 解决问题
test.get_neuron_state(pop_name="layer1", state=[ [i, ['wgtsum0',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？
test.get_neuron_state(pop_name="layer2", state=[ [i, ['wgtsum0',],] for i in range(100) ]) # 电压增大导致 第二层脉冲触发了， nice 发现问题 解决问题

In [344]:
# print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer1", state=[ [i, ['vt',],] for i in range(100) ]) # 衰减有问题，电压越来越大？？？
test.get_neuron_state(pop_name="layer2", state=[ [i, ['vt',],] for i in range(100) ]) # 电压增大导致 第二层脉冲触发了， nice 发现问题 解决问题

In [345]:
# print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer2", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器
# print(test.run_darwin3_withoutfile(spike_neurons=[[0,]]))



In [321]:
input_ls = np.array([[1 if i==1 or i == 4 else 0.2 for i in range(16)] * 16])
a = input_func(input_ls)
a

array([250], dtype=int64)

In [322]:
out = test.run_darwin3_withoutfile(spike_neurons=[a])
print(out)
# input_ls
# torch.rand(self.shape, device=self.device).le(self.source * self.unit_conversion * self.dt).type(self._backend.data_type)

[[('output_pop', 65), ('output_pop', 99)]]


In [ ]:
ls = np.zeros(100,)
def input_func(input_ls, unit_conversion=0.8, dt=0.1):# 这连个参数对标spaic的possion_encoder
    # import numpy as np
    # rand_input = np.where(np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    a = (np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    return np.nonzero(a[0].astype(int))[0]

for _ in range(25):
    input_ls = np.array([[1 if i==2 or i == 5 else 0.01 for i in range(16)] * 16])
    a = input_func(input_ls)
    out = test.run_darwin3_withoutfile(spike_neurons=[a])

    for i in range(len(out[0])):
        index = out[0][i][1]
        ls[index] += 1
print(ls.nonzero())
print(ls[ls.nonzero()])




# 那这样的话就是调出来了。 下面就是要把  Darwin的初始化还有step 的函数 放到 狗的代码里面 把spaic 的位置换成darwin stdp

(array([42, 43, 56, 69, 92], dtype=int64),)
[1. 1. 1. 1. 1.]


In [254]:
def input_func(input_ls, unit_conversion=0.8, dt=0.1):# 这连个参数对标spaic的possion_encoder
    # import numpy as np
    # rand_input = np.where(np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)
    a = (np.random.rand(*input_ls.shape) < input_ls * unit_conversion * dt)

    return np.nonzero(a[0].astype(int))[0]

In [85]:
import numpy as np

In [140]:
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\quant_input_layer1.pth")

tensor([[126.,  19.,  39.,  ...,  71.,  34.,  25.],
        [ 67.,  75.,  18.,  ...,  45.,  21.,  66.],
        [ 44.,  56.,  83.,  ...,  25.,  63., 109.],
        ...,
        [ 99.,  43.,  86.,  ..., 127., 114.,  48.],
        [123.,  67.,  39.,  ..., 105.,  42.,  78.],
        [ 92.,  52.,  49.,  ..., 127.,  47.,  39.]], device='cuda:0',
       requires_grad=True)

In [71]:
test.get_neuron_state(pop_name="layer2", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]])  # 19

In [ ]:

import time
for _ in range(25):
    print(test.run_darwin3_withoutfile(spike_neurons=[[]])) # 
    # time.sleep(0.4)
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]])  # 19

In [ ]:
print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器

In [ ]:
test.get_neuron_state(pop_name="layer2", state=[ [i, ['vt',],] for i in range(100) ])

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x05) # 查看vth 寄存器

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])

In [ ]:
import time

In [ ]:
for i in range(100):
    test.get_neuron_state(pop_name="layer1", state=[ [i, ['vt',],], ])
    time.sleep(0.5)


In [ ]:
print(test.run_darwin3_withoutfile(spike_neurons=test_ls))


In [ ]:
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器
print(test.run_darwin3_withoutfile(spike_neurons=[[]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器


In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x06) # 查看vth 寄存器

In [ ]:

print(test.run_darwin3_withoutfile(spike_neurons=[[7,]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])

# test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]]) # 查看推理存储器 这是 第四次 输入 应该进入了下一个周期，所以应该电压会相对高一点

In [ ]:
print(test.run_darwin3_withoutfile(spike_neurons=[[7,8,9]]))
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])


In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])
# test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x01)

In [ ]:
test.run_darwin3_withoutfile(spike_neurons=[[5,6,7,8],[]])
test.get_neuron_state(pop_name="layer1", state=[ [0, ['inference_status',],],  [1, ['inference_status',],]])

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x05) # 查看vth 寄存器

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_lif_200_quant\parameters\_variables.pt")

In [ ]:
test.run_darwin3_withoutfile(spike_neurons=[[]])

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x00)

In [ ]:
test.run_darwin3_withoutfile(spike_neurons=test_ls)

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['vt',],],  [1, ['vt',],] ])

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_200_quant\parameters\_parameters_dict.pt") # 加载权重
# weight_input0_to_layer1 = emo_net_weight[r'autoname9<net>_connection1<con>:autoname9<net>_layer1<neg><-autoname9<net>_input<nod>:{weight}'].detach().cpu() # 

In [ ]:
vth = torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_200\parameters\_variables.pt") # 加载权重
vth

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\save_lif_200_quant\parameters\_variables.pt") # 加载权重

In [ ]:
vth = vth['autoname9<net>_layer1<neg>:{v_th}'].detach().cpu()

In [ ]:
vth

In [ ]:
import numpy as np

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['npu_reg',],],  [1, ['npu_reg',],] ], offset=0x00)

In [ ]:
test.get_neuron_state(pop_name="layer1", state=[ [0, ['config_reg',],],  [1, ['config_reg',],] ], offset=0x16)

In [ ]:
import torch
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\quant_input_layer1.pth").detach().cpu().numpy()

In [ ]:
a[55]

In [ ]:
-24000
2**16

In [ ]:
-52 * 400

In [ ]:
3 / 32

In [ ]:
torch.load(r"C:\Users\bignuts\Desktop\ZJU\hang_zhou\alcohol\hang_zhou_spaic\save_600\real_ysc_model_mic\parameters\_parameters_dict.pt")

In [ ]:
hex(-40*400 & 0xffff)

In [360]:
tensor = torch.rand(1, 100)
tensor[0]


tensor([0.0549, 0.2530, 0.9377, 0.3443, 0.0710, 0.3346, 0.8983, 0.3832, 0.5552,
        0.3903, 0.5478, 0.6447, 0.2025, 0.3849, 0.6154, 0.7776, 0.8648, 0.9614,
        0.3548, 0.1599, 0.3912, 0.6636, 0.7701, 0.3373, 0.2571, 0.6533, 0.1603,
        0.5797, 0.6649, 0.1146, 0.3408, 0.3818, 0.2139, 0.1807, 0.3749, 0.8882,
        0.1518, 0.6336, 0.0208, 0.7863, 0.2590, 0.6219, 0.9716, 0.4132, 0.4551,
        0.0376, 0.0806, 0.2808, 0.2902, 0.3948, 0.6263, 0.9414, 0.9773, 0.8384,
        0.4529, 0.4628, 0.9641, 0.7910, 0.4829, 0.2772, 0.5739, 0.8429, 0.6505,
        0.8498, 0.7104, 0.5656, 0.7892, 0.2928, 0.8435, 0.5445, 1.0000, 0.6195,
        0.7833, 0.3110, 0.6786, 0.7452, 0.8526, 0.1661, 0.9563, 0.7899, 0.0624,
        0.9220, 0.8457, 0.1951, 0.1822, 0.8920, 0.3863, 0.5819, 0.3984, 0.5778,
        0.7062, 0.7474, 0.5513, 0.8876, 0.2124, 0.4706, 0.8848, 0.2990, 0.0203,
        0.3418])

In [365]:
# 将等于 1 的元素索引找到
torch.nonzero(tensor[0] <=0.5,as_tuple=True)[0]

tensor([ 0,  1,  3,  4,  5,  7,  9, 12, 13, 18, 19, 20, 23, 24, 26, 29, 30, 31,
        32, 33, 34, 36, 38, 40, 43, 44, 45, 46, 47, 48, 49, 54, 55, 58, 59, 67,
        73, 77, 80, 83, 84, 86, 88, 94, 95, 97, 98, 99])

In [ ]:
0b010001001000001

In [ ]:
-52*400

In [ ]:
45 * 400 

In [80]:
a = -60 * 400 
for i in range(25):
    a = a * 1.01
    print(i, a)

0 -24240.0
1 -24482.4
2 -24727.224000000002
3 -24974.496240000004
4 -25224.241202400004
5 -25476.483614424003
6 -25731.248450568244
7 -25988.560935073925
8 -26248.446544424663
9 -26510.93100986891
10 -26776.0403199676
11 -27043.80072316728
12 -27314.238730398953
13 -27587.381117702942
14 -27863.25492887997
15 -28141.88747816877
16 -28423.306352950458
17 -28707.53941647996
18 -28994.61481064476
19 -29284.560958751208
20 -29577.40656833872
21 -29873.18063402211
22 -30171.91244036233
23 -30473.63156476595
24 -30778.36788041361


In [81]:
128/24000

0.005333333333333333

In [82]:
1024/18000

0.05688888888888889